### ISSUE TITLE
Notice on empty 'classes'

### ISSUE THREAD

**Issue by szepeviktor** [cleverness/widget-css-classes#11]
Good morning!

`PHP Notice:  Undefined index: classes in /home/unlocked/website/html/static/plugins/widget-css-classes/includes/widget-css-classes.class.php on line 104`

Could you check whether it is empty?
https://github.com/cleverness/widget-css-classes/blob/master/includes/widget-css-classes.class.php#L104

**Comment by szepeviktor** [comment]
Maybe mentioning you speed things up @cleverness

**Comment by cleverness** [comment]
I will add that check next time I am working on the plugin. Thanks for letting me know about it.

**Comment by szepeviktor** [comment]
Thanks.

**Comment by JoryHogeveen** [comment]
#10 fixes this

**Comment by szepeviktor** [comment]
Thank you.
