### ISSUE TITLE
Fix Widget Logic compatibility

### ISSUE THREAD

**Issue by JoryHogeveen** [cleverness/widget-css-classes#26]
When using the `widget_content` filter option the Widget Logic compatibility isn't working anymore.

**Comment by twiginteractive** [comment]
Just to confirm - I pulled the patched code and tested in my clean WP 4.8.1 sandbox, and it works like a charm. Custom CSS classes are back even with the WL logic filter selected.

**Comment by JoryHogeveen** [comment]
Good to hear, thanks for getting back on this!
