### ISSUE TITLE
Not working in Storefront Mega Menu widgets

### ISSUE THREAD

**Issue by sagarrn23** [cleverness/widget-css-classes#28]
The plugin is not working when I add widgets in Storefront Mega Menu but works with the widgets in the sidebar.

**Comment by JoryHogeveen** [comment]
Hi @sagarchaudhari250 
That is probably because that mega menu is using the widget completally different.
I even doubt that there are integration tools for this.

But since it's a megamenu, can't you configure the columns etc. within the menu? Normally that is how mega menu's work.

**Comment by JoryHogeveen** [comment]
@sagarchaudhari250 
Let me know if/how we can help you with your issue.
We will probably need a copy of plugin in order to debug.

**Comment by JoryHogeveen** [comment]
Closing this due to no reply.
