### ISSUE TITLE
Non-custom widget classes are translated

### ISSUE THREAD

**Issue by JoryHogeveen** [cleverness/widget-css-classes#29]
Report: https://wordpress.org/support/topic/plugin-spanish-translation/#post-9427244

The `first`, `last`, `odd`, `even` and `number` widgets are translated which seems a little weird. Translations are normally for text only, not for code.
Since this plugin has 90k+ users we can't just remove it. I'd say make it an option so the users can turn it off/on.

On a fresh install: Don't enable it.
On an update with the classes enabled: Enable it to prevent issues.

**Comment by cleverness** [comment]
Let's go with an option.
