### ISSUE TITLE
Readme updates

### ISSUE THREAD

**Issue by JoryHogeveen** [cleverness/widget-css-classes#31]
@cleverness 
I'd like to hear your thoughts on the ideas below for the readme file.

- **Plugin website** > Move to GitHub Wiki or update website after each update. We can create a website link on the GitHub Wiki.
  - We can add documentation on the wiki as well, example: https://github.com/JoryHogeveen/view-admin-as/wiki
- **Credits** as a list item (more compact)
- **Licence** can be removed since there is a licence file within the plugin. All plugins on WP.org are GPL compatible.
- **FAQ**
  - Apply correct markup
  - Bug reporting: Change links to GitHub so contributors can help if possible.
  - Add numbers for FAQ questions

**Comment by cleverness** [comment]
Moving it to Github Wiki would be good. The website is very out of date.

The other changes are good too.
