### ISSUE TITLE
Conflict with one setting in dFactory Repsonsive Lightbox plugin

### ISSUE THREAD

**Issue by woolfa** [cleverness/widget-css-classes#33]
## Expected Behavior
Custom classes can be added to widgets.

## Actual Behavior
Custom classes (text or predefined) do not get written out to html, but are displayed in Widget UI.  Even custom widget css classes built into theme no longer work.  The standard ones do get written out to html successfully (widget-first, widget-last, etc)

## Steps to Reproduce the Problem

  1. Install dFactory Responsive Lightbox plugin v 1.7.2  ( https://wordpress.org/plugins/responsive-lightbox/ )
  2. Goto Plugin Settings, and General Settings tab
  3. Select either "PrettyPhoto" or "Featherlight" as Default Lightbox  (only tested with these two and the paid "Lightcase" that I purchased)
  4. Check the box (enable) for "Widgets :    Enable lightbox for widgets content."
  5.  Click Save at bottom.
  6.  Clear browser cache, and reload site to see issue.
  7.  Tried deactivating and deleting Widget CSS Classes and reinstalling, but issue persisted.
  8.  Disabled Repsonsive Lightbox setting for widget contents to resolve.
 
## Notes

  - I use a page caching plugin, but cleared cache for all test steps.

## Specifications

  - Plugin Version:  1.5.2.1
  - WordPress Version: 4.9.1
  - Other plugins installed:  many listed in attached image.  Issue occurred on installing and configuring Responsive Lightbox
  - Theme:  Shaped Pixels v 1.1.2 ( http://shapedpixels.com )
  - Browser:  On Mac, tested with current versions of Firefox, Chrome and Safari 

![plugin-list](https://user-images.githubusercontent.com/34987045/34463327-53f0eaf0-ee26-11e7-9a7c-2260a70a6e95.jpg)

**Comment by JoryHogeveen** [comment]
Hi @woolfa 
Thank you for reporting!
I'm guessing that that plugin hooks into the same area as this one when enabled for widgets. I'll check the code asap to see if I can come up with a neat compatibility fix.

**Comment by JoryHogeveen** [comment]
Error found and possibly fixed, but.. do you know the actual purpose of that setting? If I disable the widget setting the widget fancyboxes still work..

**Comment by JoryHogeveen** [comment]
Got it, it's for the WYSIWYG widgets as far as I can see. Got a patch pushed to the `dev` branch.
If you would like to test it as well that would be great!
Please check the referenced pull request v1.5.3 (#34).

**Comment by woolfa** [comment]
Tested v1.5.3 and that works perfectly now.  Thank you for quick response!

**Comment by woolfa** [comment]
...and, not sure what the setting exactly does in Responsive Lightbox plug-in.  Not familiar enough with it yet.

**Comment by JoryHogeveen** [comment]
@woolfa 
Ok perfect, thanks!
I found that this impacts auto-lightbox handling for text/wysiwyg widgets. Maybe also other widgets, not sure.
I'll try to make an official update a.s.a.p.!
