### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by simplethemes** [cleverness/widget-css-classes#4]
Hi, I'd like to be able to import widget class settings via theme level.

Can you provide an example of how this might be done and still allow the user to modify the settings? Would you recommend attaching this to after_theme_setup? Thanks!

`update_option( 'WCSSC_options', $options );`

**Comment by JoryHogeveen** [comment]
Hi @simplethemes 
The next release will feature a new hook for this: `widget_css_classes_set_settings`.
Within that hook you can overwrite the plugin settings on theme level.

> still allow the user to modify the settings
This might be tricky. It will involve changing the default settings I suppose. I will think about how to do this and reply here.

**Comment by JoryHogeveen** [comment]
Default settings should indeed work for this. I've added the feature in #22
